# -*- coding: utf-8 -*-
"""Hollywood Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tW5KvdwtbTS9pK-o0HVc3ge6Gi7Bpuz
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("aditya126/movies-box-office-dataset-2000-2024")

print("Path to dataset files:", path)
path = kagglehub.dataset_download("ashenp/tmdb-box-office-dataset-for-prediction")

print("Path to dataset files:", path)

import pandas as pd
import os

# Define the paths you provided
tmdb_path = "/kaggle/input/tmdb-box-office-dataset-for-prediction/dataset_1_collected_data.csv"
box_office_path = "/kaggle/input/movies-box-office-dataset-2000-2024/enhanced_box_office_data(2000-2024)u.csv"

# Verify if the files actually exist there
print("TMDB File Exists:", os.path.exists(tmdb_path))
print("Box Office File Exists:", os.path.exists(box_office_path))

# Let's try to load just the first 5 rows to make sure they open smoothly
try:
    tmdb_preview = pd.read_csv(tmdb_path, nrows=5)
    box_preview = pd.read_csv(box_office_path, nrows=5)
    print("\nFiles loaded successfully! We are ready for Part 2.")
except Exception as e:
    print(f"\nOops, something went wrong: {e}")

import pandas as pd

# Define paths
tmdb_path = "/kaggle/input/tmdb-box-office-dataset-for-prediction/dataset_1_collected_data.csv"
box_office_path = "/kaggle/input/movies-box-office-dataset-2000-2024/enhanced_box_office_data(2000-2024)u.csv"

# Load the full datasets
tmdb_df = pd.read_csv(tmdb_path)
box_office_df = pd.read_csv(box_office_path)

print("="*60)
print("1. DATASET SHAPE & COLUMN NAMES")
print("="*60)
print(f"TMDB Dataset: {tmdb_df.shape[0]} rows, {tmdb_df.shape[1]} columns")
print(f"Columns: {list(tmdb_df.columns)}\n")

print(f"Box Office Dataset: {box_office_df.shape[0]} rows, {box_office_df.shape[1]} columns")
print(f"Columns: {list(box_office_df.columns)}\n")

print("="*60)
print("2. NULL VALUE COUNT")
print("="*60)
print("--- Missing in TMDB ---")
print(tmdb_df.isnull().sum())
print("\n--- Missing in Box Office ---")
print(box_office_df.isnull().sum())

print("\n" + "="*60)
print("3. DATA PREVIEWS (First 2 Rows)")
print("="*60)
print("--- TMDB Sample ---")
display(tmdb_df.head(2))
print("\n--- Box Office Sample ---")
display(box_office_df.head(2))

import pandas as pd

# Define paths
tmdb_path = "/kaggle/input/tmdb-box-office-dataset-for-prediction/dataset_1_collected_data.csv"
box_office_path = "/kaggle/input/movies-box-office-dataset-2000-2024/enhanced_box_office_data(2000-2024)u.csv"

# Load the full datasets
tmdb_df = pd.read_csv(tmdb_path)
box_office_df = pd.read_csv(box_office_path)

# 1. Create matching keys by making titles lowercase and removing stray whitespace
tmdb_df['title_clean'] = tmdb_df['title'].astype(str).str.strip().str.lower()
box_office_df['title_clean'] = box_office_df['Release Group'].astype(str).str.strip().str.lower()

# 2. Perform the inner merge
merged_df = pd.merge(
    box_office_df,
    tmdb_df,
    on='title_clean',
    how='inner',
    suffixes=('_box', '_tmdb')
)

print("="*60)
print("MERGE RESULTS")
print("="*60)
print(f"Total matching movies successfully merged: {merged_df.shape[0]}")
print(f"Columns available in the new merged dataset:\n{list(merged_df.columns)}")

print("\n" + "="*60)
print("MERGED DATA PREVIEW (First Row)")
print("="*60)
display(merged_df[['Release Group', 'title', '$Worldwide', 'budget', 'cast', 'director']].head(1))

import pandas as pd

# (We assume merged_df is carried over from your previous cell)

print("="*60)
print("PART 4: CLEANING FINANCIAL & RUNTIME DATA")
print("="*60)

# 1. Clean the target column ($Worldwide)
# We remove '$' and ',' and convert to numeric, making errors NaN so we can drop them easily
merged_df['worldwide_gross'] = pd.to_numeric(
    merged_df['$Worldwide'].astype(str).str.replace('$', '').str.replace(',', ''),
    errors='coerce'
)

# 2. Clean the features columns (budget and runtime)
merged_df['budget_clean'] = pd.to_numeric(merged_df['budget'], errors='coerce')
merged_df['runtime_clean'] = pd.to_numeric(merged_df['runtime'], errors='coerce')

# Record starting count
initial_count = merged_df.shape[0]

# 3. Apply the threshold filters (> $100k budget/gross and valid runtime)
cleaned_df = merged_df[
    (merged_df['worldwide_gross'] >= 100000) &
    (merged_df['budget_clean'] >= 100000)
].copy()

# Drop rows where critical numbers are completely missing
cleaned_df.dropna(subset=['worldwide_gross', 'budget_clean', 'runtime_clean'], inplace=True)

final_count = cleaned_df.shape[0]

print(f"Initial merged records: {initial_count}")
print(f"Cleaned records remaining after filtering: {final_count}")
print(f"Removed {initial_count - final_count} rows with invalid or incomplete financials/runtimes.")

print("\n" + "="*60)
print("CLEANED DATA SUMMARY STATS")
print("="*60)
print(cleaned_df[['worldwide_gross', 'budget_clean', 'runtime_clean']].describe().round(2))

import pandas as pd

# (Using cleaned_df from your previous cell)

print("="*60)
print("PART 5: CREATING SEASONALITY FEATURES")
print("="*60)

# 1. Convert release_date to datetime (coercing invalid formats to NaT)
cleaned_df['release_date_dt'] = pd.to_datetime(cleaned_df['release_date'], errors='coerce')

# Drop any rows where release_date is missing or broke during parsing
cleaned_df.dropna(subset=['release_date_dt'], inplace=True)

# 2. Extract key time features
cleaned_df['release_month'] = cleaned_df['release_date_dt'].dt.month
cleaned_df['release_year'] = cleaned_df['release_date_dt'].dt.year

# 3. Create the Seasonality Flags (1 for Yes, 0 for No)
cleaned_df['is_summer'] = cleaned_df['release_month'].isin([6, 7, 8]).astype(int)
cleaned_df['is_holiday'] = cleaned_df['release_month'].isin([11, 12]).astype(int)

print(f"Features created successfully! Total rows preserved: {cleaned_df.shape[0]}")

print("\n" + "="*60)
print("SEASONAL DISTRIBUTION OF MOVIES")
print("="*60)
print(f"Summer Releases (Jun-Aug): {cleaned_df['is_summer'].sum()}")
print(f"Holiday Releases (Nov-Dec): {cleaned_df['is_holiday'].sum()}")
print(f"Other Months: {cleaned_df.shape[0] - cleaned_df['is_summer'].sum() - cleaned_df['is_holiday'].sum()}")

print("\n" + "="*60)
print("AVERAGE WORLDWIDE GROSS BY SEASON")
print("="*60)
avg_summer = cleaned_df[cleaned_df['is_summer'] == 1]['worldwide_gross'].mean()
avg_holiday = cleaned_df[cleaned_df['is_holiday'] == 1]['worldwide_gross'].mean()
avg_other = cleaned_df[(cleaned_df['is_summer'] == 0) & (cleaned_df['is_holiday'] == 0)]['worldwide_gross'].mean()

print(f"Summer Movies average:  ${avg_summer:,.2f}")
print(f"Holiday Movies average: ${avg_holiday:,.2f}")
print(f"Other Months average:   ${avg_other:,.2f}")

import pandas as pd
import networkx as nx
import ast

# (Using cleaned_df from your previous cell)

print("="*60)
print("PART 6: BUILDING THE NETWORKX GRAPH")
print("="*60)

# Initialize an undirected graph
G = nx.Graph()

# Safety function to parse stringified lists safely (e.g. "['Actor A', 'Actor B']" -> ['Actor A', 'Actor B'])
def safe_parse_list(val):
    if pd.isna(val):
        return []
    if isinstance(val, list):
        return val
    try:
        # ast.literal_eval is safer than eval
        return ast.literal_eval(val)
    except:
        # If it's a raw comma-separated string instead of a Python list string
        return [item.strip() for item in str(val).split(',') if item.strip()]

# 1. Parse cast and director columns into clean Python lists
cleaned_df['cast_parsed'] = cleaned_df['cast'].apply(safe_parse_list)

# For directors, let's treat them as lists too in case a movie has co-directors
cleaned_df['director_parsed'] = cleaned_df['director'].apply(safe_parse_list)

# 2. Populate the graph with nodes and edges
for idx, row in cleaned_df.iterrows():
    movie_node = f"MOVIE_{row['title_clean']}"

    # Add the movie node
    G.add_node(movie_node, type='movie')

    # Add cast members and connect them to this movie
    for actor in row['cast_parsed']:
        actor_node = f"ACTOR_{actor.strip().lower()}"
        G.add_node(actor_node, type='actor')
        G.add_edge(movie_node, actor_node)

    # Add directors and connect them to this movie
    for director in row['director_parsed']:
        director_node = f"DIRECTOR_{director.strip().lower()}"
        G.add_node(director_node, type='director')
        G.add_edge(movie_node, director_node)

print("Graph constructed successfully!")
print(f"Total Nodes: {G.number_of_nodes()}")
print(f"Total Edges (Connections): {G.number_of_edges()}")

# Let's see some basic degree properties (who has the most direct connections?)
degrees = dict(G.degree())
# Filter degrees to only show actor/director nodes to see the busiest professionals
people_degrees = {k: v for k, v in degrees.items() if not k.startswith("MOVIE_")}
sorted_people = sorted(people_degrees.items(), key=lambda x: x[1], reverse=True)

print("\n" + "="*60)
print("MOST CONNECTED INDUSTRY PROFESSIONALS IN GRAPH (Direct Connections)")
print("="*60)
for name, degree in sorted_people[:10]:
    clean_name = name.replace("ACTOR_", "").replace("DIRECTOR_", "").title()
    role = "Actor" if name.startswith("ACTOR_") else "Director"
    print(f"{clean_name} ({role}): connected to {degree} movies")

import pandas as pd
import networkx as nx

# (Using cleaned_df and G from your previous cells)

print("="*60)
print("PART 7: CALCULATING PAGERANK STAR-POWER SCORES")
print("="*60)

# 1. Run PageRank on the entire graph G
pagerank_scores = nx.pagerank(G)

# Helper functions to calculate cumulative star power scores for each movie row
def get_cast_power(cast_list):
    total_power = 0.0
    for actor in cast_list:
        actor_node = f"ACTOR_{actor.strip().lower()}"
        # If the actor exists in our graph PageRank scores, add their score
        total_power += pagerank_scores.get(actor_node, 0.0)
    return total_power

def get_director_power(director_list):
    total_power = 0.0
    for director in director_list:
        director_node = f"DIRECTOR_{director.strip().lower()}"
        total_power += pagerank_scores.get(director_node, 0.0)
    return total_power

# 2. Map the calculated network scores back to our main DataFrame
cleaned_df['cast_star_power'] = cleaned_df['cast_parsed'].apply(get_cast_power)
cleaned_df['director_star_power'] = cleaned_df['director_parsed'].apply(get_director_power)

print("Star-power metrics successfully engineered!")

# 3. Print a quick comparison to see how the metrics look
print("\n" + "="*60)
print("SAMPLE MOVIES WITH ENGINEERED STAR-POWER SCORES")
print("="*60)
display(cleaned_df[['title', 'cast_star_power', 'director_star_power', 'worldwide_gross']].head(5))

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

# (Using cleaned_df from your previous cell)

print("="*60)
print("PART 8: DATA PREPARATION & SPLITTING")
print("="*60)

# 1. Define feature columns (X) and target column (y)
feature_cols = [
    'budget',
    'runtime',
    'is_summer',
    'is_holiday',
    'cast_star_power',
    'director_star_power'
]

X = cleaned_df[feature_cols]
y = cleaned_df['worldwide_gross']

# 2. Perform 80/20 Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Data split successfully!")
print(f"Training set size: {X_train.shape[0]} movies")
print(f"Testing set size:  {X_test.shape[0]} movies")

# 3. Scale the features (highly recommended for linear models & neural nets)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert scaled arrays back to DataFrames for easy exploration
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=feature_cols)

print("\n" + "="*60)
print("SCALED TRAINING FEATURES PREVIEW (First 3 Rows)")
print("="*60)
display(X_train_scaled_df.head(3))

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import pandas as pd
import numpy as np

# (Using scaled features and y from your previous cells)

print("="*60)
print("PART 9: TRAINING AND EVALUATING MODELS")
print("="*60)

# 1. Initialize and train Linear Regression
lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)
lr_preds = lr_model.predict(X_test_scaled)

# 2. Initialize and train Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_preds = rf_model.predict(X_test_scaled)

# 3. Calculate metrics for Linear Regression
lr_mae = mean_absolute_error(y_test, lr_preds)
lr_r2 = r2_score(y_test, lr_preds)

# 4. Calculate metrics for Random Forest
rf_mae = mean_absolute_error(y_test, rf_preds)
rf_r2 = r2_score(y_test, rf_preds)

print("Models trained successfully!\n")

# Print Evaluation Summary
print("="*60)
print("EVALUATION METRICS COMPARISON")
print("="*60)
print(f"Linear Regression:")
print(f"  - Mean Absolute Error (MAE): ${lr_mae:,.2f}")
print(f"  - R-squared (R²) Score:     {lr_r2:.4f}")
print("-" * 60)
print(f"Random Forest Regressor:")
print(f"  - Mean Absolute Error (MAE): ${rf_mae:,.2f}")
print(f"  - R-squared (R²) Score:     {rf_r2:.4f}")

import pandas as pd
import numpy as np

# (Using rf_model and feature_cols from your previous cells)

print("="*60)
print("PART 10: FEATURE IMPORTANCE & KEY INSIGHTS")
print("="*60)

# Extract feature importances from Random Forest
importances = rf_model.feature_importances_

# Create a clean DataFrame to display them
importance_df = pd.DataFrame({
    'Feature': feature_cols,
    'Importance (%)': importances * 100
})

# Sort by importance
importance_df = importance_df.sort_values(by='Importance (%)', ascending=False).reset_index(drop=True)

# Format the output
print("Relative influence of each feature on predicted box office:")
print("-" * 60)
for index, row in importance_df.iterrows():
    print(f"{index + 1}. {row['Feature'].upper():<22} : {row['Importance (%)']:.2f}%")
print("="*60)

# 1. Grab the real-world historical PageRank values for Christopher Nolan and his massive cast
def lookup_node_score(name):
    # Lookup in our pagerank registry, defaulting to the median value for any new names
    node_name = f"ACTOR_{name.lower().strip()}" if name != "Christopher Nolan" else f"DIRECTOR_{name.lower().strip()}"
    return pagerank_scores.get(node_name, np.median(list(pagerank_scores.values())))

# The Odyssey Cast: Matt Damon, Tom Holland, Anne Hathaway, Robert Pattinson, Zendaya
cast_list = ["Matt Damon", "Tom Holland", "Anne Hathaway", "Robert Pattinson", "Zendaya"]
odyssey_cast_score = sum(lookup_node_score(actor) for actor in cast_list)
odyssey_director_score = lookup_node_score("Christopher Nolan")

# 2. Build the input row: Budget ($250M), Runtime (172 mins), Summer Release (1), Holiday Release (0), Cast Score, Director Score
odyssey_raw_features = pd.DataFrame([[
    250000000,
    172,
    1,
    0,
    odyssey_cast_score,
    odyssey_director_score
]], columns=feature_cols)

# 3. Scale the inputs using the exact same scaler we trained our models on
odyssey_scaled_features = scaler.transform(odyssey_raw_features)

# 4. Generate the prediction
predicted_gross = rf_model.predict(odyssey_scaled_features)[0]

print("="*60)
print("             THE ODYSSEY (2026) FINAL FORECAST")
print("="*60)
print(f"Production Budget:         $250,000,000.00")
print(f"Runtime:                   172 Minutes")
print(f"Release Timing:            Peak Summer (July)")
print(f"Director:                  Christopher Nolan")
print(f"Star-Power Cast Score:     {odyssey_cast_score:.6f}")
print("-" * 60)
print(f"MODEL PREDICTED WORLDWIDE GROSS: ${predicted_gross:,.2f}")
print(f"Estimated ROI:             {((predicted_gross - 250000000) / 250000000 * 100):.1f}%")
print("="*60)

